name: On Release

on:
  release:
    types: [ created ]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: echo ${{ github.event.release.tag_name }}
