name: On Release

on:
  release:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - run: echo '${github.ref##*/}'
      - run: echo '${${{ github.ref }}##*/}'
      - run: echo '${{ github.ref }}##*/
