name: Test the push
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        id: version
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          last-version: v0.1.0
          prefix: v

      - name: Get output
        run: echo "Next version is ${{ steps.version.outputs.next }}"
