name: Test the repository dispatch
on:
  repository_dispatch:
    types: [release]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        id: version
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          prefix: v

      - name: Get output
        run: echo "Next version is ${{ steps.version.outputs.next }} (${{ steps.version.outputs.type }})"
